### ISSUE TITLE
サンプルが動かない

### ISSUE THREAD

**Issue by renon0827** [sandy-sunday/vid2pano#1]
下記の様なエラーが発生しており、変換が行われませんでした。

OS: Windows10 Pro
```
E:\work\vid2pano>python --version
Python 3.9.6

E:\work\vid2pano>pip install -r requirements.txt
Requirement already satisfied: opencv-python in (ホームディレクトリ)\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 1)) (4.6.0.66)
Requirement already satisfied: numpy in (ホームディレクトリ)\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 2)) (1.23.3)

[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

E:\work\vid2pano>python main.py
Traceback (most recent call last):
  File "E:\work\vid2pano\main.py", line 32, in <module>
    main()
  File "E:\work\vid2pano\main.py", line 12, in main
    vid2pano(video)
  File "E:\work\vid2pano\main.py", line 25, in vid2pano
    image_name = panoramaMapper.main()
  File "E:\work\vid2pano\panoramaMapper.py", line 21, in main
    frames = imageLoader("./frames/")
  File "E:\work\vid2pano\panoramaMapper.py", line 12, in imageLoader
    for filename in os.listdir(folder):
FileNotFoundError: [WinError 3] 指定されたパスが見つかりません。: './frames/'
```

**Comment by renon0827** [comment]
Framesディレクトリを追加したところ、正しく動作しました。
Readmeへの追記のPR後、本IssueはCloseします。

**Comment by renon0827** [comment]
PR作成しました。ご確認お願い致します
https://github.com/sandy-sunday/vid2pano/pull/2
